# you will haxe to start a temporary webserver so textures can be loaded and used by webgl
# call "nekotools server" for instance

all: t01 t02 t03 t04

t01:
	haxe -lib three.js -debug -main T01 -js t01.js

t02:
	haxe -lib three.js -debug -main T02 -js t02.js

t03:
	haxe -lib three.js -debug -main T03 -js t03.js

t04:
	haxe -dce no -lib three.js -debug -main T04 -js t04.js
