package js.three;

// Note: BinaryLoader.prototype.createBinModel contains a Model definition
@:native("THREE.BinaryLoader")
extern class BinaryLoader extends Loader {
    public var showProgress : Bool;
    public var texturePath : String;
    public var binaryPath : String;
    public function new(?showStatus:Bool) : Void;
    // Load models generated by slim OBJ converter with BINARY option (converter_obj_three_slim.py -t binary)
    //  - binary models consist of two files: JS and BIN
    //  - parameters
    //      - url (required)
    //      - callback (required)
    //      - texturePath (optional: if not specified, textures will be assumed to be in the same folder as JS model file)
    //      - binaryPath (optional: if not specified, binary file will be assumed to be in the same folder as JS model file)
    public function load(url:String, resultCallback:Model->Void, ?texturePath:String, ?binaryPath:String) : Void;
}
