package js.three;

@:native("THREE.UTF8Loader")
extern class UTF8Loader {
    public function new() : Void;
    /**
     * Loader for UTF8 encoded models generated by:
     *  http://code.google.com/p/webgl-loader/
     *
     * Limitations:
     *  - number of vertices < 65536 (this is after optimizations in compressor, input OBJ may have even less)
     *  - models must have normals and texture coordinates
     *  - texture coordinates must be only from <0,1>
     *  - no materials support yet
     *  - models are scaled and offset (copy numbers from compressor and use them as parameters in UTF8Loader.load() )
     *
     * @author alteredq / http://alteredqualia.com/
     * @author won3d / http://twitter.com/won3d
     */
    // Load UTF8 compressed models generated by objcompress
    //  - parameters
    //      - url (required)
    //      - callback (required)
    //      - metaData (optional)
    public function load(url:String, resultCallback:Model->Void, metaData:{ scale:Float, offsetX:Float, offsetY:Float, offsetZ:Float }) : Void;
    // TODO createMesh
}
